services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile_api
    ports:
      - "10000:8000"
    volumes:
      - .:/app
       # Dedicated volume for MLflow

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile_dashboard
    ports:
      - "10001:8501"
    volumes:
      - .:/app
      


volumes:
  mlflow_data: