services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - mlflow_data:/app/mlruns  # Dedicated volume for MLflow

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - mlflow_data:/app/mlruns  


volumes:
  mlflow_data: